//! Embed the conformance suite in the binary.
//!
//! `ingot conform` used to need a checkout: it searched upward for
//! `specs/conformance` and refused if it found none. That makes the suite
//! something you can read on GitHub rather than something you can run, which is
//! the opposite of what a conformance suite is for.
//!
//! So the cases travel with the binary. A backend author downloads `ingot`,
//! points it at their command, and gets a verdict — no clone, no version to
//! keep in step. The suite tests conformance to *this* toolchain's
//! specifications, so binding it to the binary's version is not a compromise;
//! it is the correct coupling.
//!
//! The same technique the Python backend already uses for its prelude, one
//! directory wider.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("cargo sets this"))
        .parent()
        .and_then(Path::parent)
        .expect("the crate lives two levels below the repository root")
        .join("specs")
        .join("conformance");

    let mut files = BTreeSet::new();
    collect(&root, &root, &mut files);

    // Rerun on any change under the suite, including a file appearing or going
    // away — a directory's own mtime moves when its entries do.
    println!("cargo:rerun-if-changed={}", root.display());
    for relative in &files {
        println!("cargo:rerun-if-changed={}", root.join(relative).display());
    }

    let mut out = String::from(
        "// Generated by build.rs. The conformance suite, as it was at compile time.\n\
         pub const FILES: &[(&str, &[u8])] = &[\n",
    );
    for relative in &files {
        // Forward slashes on both sides: rustc accepts them in `include_bytes!`
        // on every platform, and the key is a suite-relative path that a
        // `--export` writes back out.
        let key = relative.replace('\\', "/");
        let absolute = root.join(relative).display().to_string().replace('\\', "/");
        out.push_str(&format!("    ({key:?}, include_bytes!({absolute:?})),\n"));
    }
    out.push_str("];\n");

    let generated = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets this"))
        .join("conformance_suite.rs");
    std::fs::write(&generated, out).expect("writing the generated suite");
}

/// Every file under `dir`, as a path relative to `base`.
fn collect(base: &Path, dir: &Path, out: &mut BTreeSet<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, out);
            continue;
        }
        // `tools/` is a worked example an author reads in the repository, not
        // something a run needs. Embedding it would put a Python script in
        // every binary for nobody's benefit.
        let Ok(relative) = path.strip_prefix(base) else {
            continue;
        };
        if relative.starts_with("tools") {
            continue;
        }
        out.insert(relative.display().to_string());
    }
}
