[package]
name = "ingot-semantic"
description = "Name resolution, type checking and effect/policy analysis for Ingot."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ingot-source.workspace = true
ingot-diagnostics.workspace = true
ingot-syntax.workspace = true
ingot-lang-types.workspace = true

[dev-dependencies]
ingot-parser.workspace = true
